import { ArrowLeft, CreditCard, Heart, Megaphone, MessageCircle, Star, UserPlus, Wallet } from 'lucide-react';
import type { ReactNode } from 'react';
import { useCallback, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { userService } from '../api/services';
import { AsyncState } from '../components/common/AsyncState';
import { useAsync } from '../hooks/useAsync';
import { won } from '../utils/format';

function Top({ title, subtitle, right }: { title: string; subtitle?: string; right?: ReactNode }) {
  const nav = useNavigate();
  return <header className="account-top"><button onClick={()=>nav(-1)} aria-label="뒤로"><ArrowLeft/></button>{right}<h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</header>;
}

function useToast(){const [toast,setToast]=useState('');return [toast,(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2000);}] as const;}

export function WishlistPage(){const load=useCallback(()=>userService.wishlist(),[]);const {data,loading,error,retry}=useAsync(load);const [removed,setRemoved]=useState<string[]>([]);const [toast,notify]=useToast();if(loading||error||!data)return <div className="page"><AsyncState loading={loading} error={error} onRetry={retry}/></div>;const shown=data.filter(w=>!removed.includes(w.id));return <div className="page account-page"><h1>관심 클래스</h1><p className="account-lead">찜한 클래스를 모아봤어요</p><div className="student-stack">{shown.map(w=><Link className="student-class-card market wishlist-card" to={`/learn/classes/${w.id}`} key={w.id}><i style={{background:`linear-gradient(135deg,${w.color},color-mix(in srgb, ${w.color}, white 35%))`}}/><span><b>{w.title}</b><small>{w.meta}</small><strong>{w.price}</strong></span><button aria-label="관심 해제" onClick={(e)=>{e.preventDefault();setRemoved([...removed,w.id]);notify('관심 클래스에서 해제했어요');}}><Heart fill="currentColor"/></button></Link>)}</div><AsyncState loading={false} empty={!shown.length}/>{toast&&<div className="done-toast" aria-live="polite">{toast}</div>}</div>}

const iconMap={apply:UserPlus,pay:CreditCard,review:Star,settle:Wallet,notice:Megaphone};
export function NotificationsPage(){const [read,setRead]=useState(false);const load=useCallback(()=>userService.notifications(),[]);const {data,loading,error,retry}=useAsync(load);if(loading||error||!data)return <div className="page"><AsyncState loading={loading} error={error} onRetry={retry}/></div>;const groups=[...new Set(data.map(n=>n.group))];return <div className="page account-page no-bottom"><Top title="알림" right={<button className="read-all" onClick={()=>{setRead(true);void userService.markNotificationsRead();}}>모두 읽음</button>}/>{groups.map(group=><section className="notice-group" key={group}><h3>{group}</h3>{data.filter(n=>n.group===group).map(n=>{const Icon=iconMap[n.type];const unread=n.unread&&!read;return <button className={`notice-row ${unread?'unread':''}`} key={n.id}><i className={n.type}><Icon/></i><span><b>{n.title}{unread&&<em/>}</b><small>{n.message}</small></span><time>{n.time}</time></button>})}</section>)}</div>}

export function SettlementPage(){const load=useCallback(()=>userService.settlement(),[]);const {data,loading,error,retry}=useAsync(load);const [toast,notify]=useToast();if(loading||error||!data)return <div className="page"><AsyncState loading={loading} error={error} onRetry={retry}/></div>;return <div className="page account-page no-bottom"><Top title="정산 관리" subtitle="클래스 수익을 확인하고 출금하세요"/><section className="settle-hero"><small>출금 가능 금액</small><b>{won(data.availableAmount)}</b><p>이번 달 정산 예정 {won(data.expectedAmount)}</p><button onClick={()=>notify('출금 신청이 접수됐어요')}>출금하기</button><i/></section><div className="stats settle-stats">{data.stats.map(s=><div key={s.label}><b style={{color:s.color}}>{s.value}</b><small>{s.label}</small></div>)}</div><button className="account-card account-bank" onClick={()=>notify('계좌 변경은 본인 인증 후 가능해요')}><i><CreditCard/></i><span><small>정산 계좌</small><b>{data.account}</b></span><em>변경</em></button><h3>정산 내역</h3><div className="menu-box">{data.rows.map(r=><div className="settle-row" key={r.id}><span><b>{r.title}</b><small>{r.date}</small></span><em className={r.status}>{r.amount}<small>{r.status==='wait'?'정산 예정':'정산 완료'}</small></em></div>)}</div>{toast&&<div className="done-toast" aria-live="polite">{toast}</div>}</div>}

export function NotificationSettingsPage(){const load=useCallback(()=>userService.notificationSettings(),[]);const {data,loading,error,retry}=useAsync(load);const [local,setLocal]=useState<Record<string,boolean>>({});if(loading||error||!data)return <div className="page"><AsyncState loading={loading} error={error} onRetry={retry}/></div>;const enabled=(key:string,base:boolean)=>local[key]??base;const toggle=(key:string,base:boolean)=>{const next=!enabled(key,base);setLocal({...local,[key]:next});void userService.updateNotificationSetting(key,next);};return <div className="page account-page no-bottom"><Top title="알림 설정" subtitle="받고 싶은 알림을 선택하세요"/>{(['push','marketing'] as const).map(group=><section className="setting-section" key={group}><h3>{group==='push'?'푸시 알림':'마케팅 · 기타'}</h3><div className="menu-box">{data.filter(s=>s.group===group).map(s=><div className="toggle-row" key={s.key}><span><b>{s.label}</b><small>{s.description}</small></span><button className={enabled(s.key,s.enabled)?'on':''} onClick={()=>toggle(s.key,s.enabled)}><i/></button></div>)}{group==='marketing'&&<div className="toggle-row"><span><b>방해 금지 시간</b><small>이 시간엔 알림을 보내지 않아요</small></span><em>밤 10시 ~ 오전 8시</em></div>}</div></section>)}<p className="hint">중요한 결제·정산 알림은 설정과 관계없이 발송될 수 있어요.</p></div>}

export function SupportPage(){const load=useCallback(()=>userService.faqs(),[]);const {data,loading,error,retry}=useAsync(load);const [open,setOpen]=useState(0);const [toast,notify]=useToast();if(loading||error||!data)return <div className="page"><AsyncState loading={loading} error={error} onRetry={retry}/></div>;return <div className="page account-page no-bottom"><Top title="고객센터" subtitle="궁금한 점을 빠르게 해결해드려요"/><div className="support-actions"><button onClick={()=>notify('1:1 문의가 접수됐어요')}><MessageCircle/><b>1:1 문의</b><small>보통 1시간 내 답변</small></button><button onClick={()=>notify('카카오톡 상담으로 연결할게요')}><i>k</i><b>카카오톡 문의</b><small>평일 10:00~18:00</small></button></div><h3>자주 묻는 질문</h3><div className="menu-box faq-box">{data.map((f,i)=><div key={f.id}><button onClick={()=>setOpen(open===i?-1:i)}><b>Q</b><span>{f.question}</span></button>{open===i&&<p>{f.answer}</p>}</div>)}</div><section className="support-info"><b>고객센터 안내</b><p><span>운영 시간</span><strong>평일 10:00~18:00</strong></p><p><span>이메일</span><strong>help@oneclick.class</strong></p></section>{toast&&<div className="done-toast" aria-live="polite">{toast}</div>}</div>}

export function SettingsPage(){const [dark,setDark]=useState(false);const [toast,notify]=useToast();return <div className="page account-page no-bottom"><Top title="설정"/><MenuSection title="계정" notify={notify} rows={[['프로필 수정',''],['비밀번호 변경',''],['결제 관리','/payment']]}/><section className="setting-section"><h3>화면</h3><div className="menu-box"><div className="toggle-row"><span><b>다크 모드</b><small>어두운 화면으로 보기</small></span><button className={dark?'on':''} onClick={()=>{setDark(!dark);notify(dark?'라이트 모드로 변경했어요':'다크 모드로 변경했어요');}}><i/></button></div><button className="menu-row" onClick={()=>notify('언어는 한국어로 설정되어 있어요')}><span>언어</span><em>한국어</em></button></div></section><MenuSection title="정보" notify={notify} rows={[['공지사항',''],['이용약관',''],['개인정보 처리방침',''],['버전 정보','']]}/><Link className="logout" to="/login">로그아웃</Link><button className="leave" onClick={()=>notify('탈퇴 전 고객센터 확인이 필요해요')}>회원 탈퇴</button>{toast&&<div className="done-toast" aria-live="polite">{toast}</div>}</div>}

function MenuSection({title,rows,notify}:{title:string;rows:[string,string][];notify?:(message:string)=>void}){return <section className="setting-section"><h3>{title}</h3><div className="menu-box">{rows.map(([label,to])=>to?<Link className="menu-row" to={to} key={label}><span>{label}</span></Link>:<button className="menu-row" key={label} onClick={()=>notify?.(label==='버전 정보'?'최신 버전을 사용 중이에요':`${label} 화면을 준비했어요`)}><span>{label}</span>{label==='버전 정보'&&<em>1.4.2 · 최신</em>}</button>)}</div></section>}

export function PaymentPage(){const load=useCallback(()=>userService.payment(),[]);const {data,loading,error,retry}=useAsync(load);const [defaultId,setDefaultId]=useState('');const [toast,notify]=useToast();if(loading||error||!data)return <div className="page"><AsyncState loading={loading} error={error} onRetry={retry}/></div>;const selected=defaultId||data.methods.find(m=>m.isDefault)?.id;return <div className="page account-page no-bottom"><Top title="결제 관리" subtitle="요금제와 결제 수단을 관리하세요"/><section className="plan-card"><span>이용 중인 요금제</span><button onClick={()=>notify('플랜 변경 화면을 준비했어요')}>플랜 변경</button><b>{data.plan}</b><p>{data.price} · 다음 결제일 {data.nextBillingDate}</p></section><h3>결제 수단</h3><div className="payment-methods">{data.methods.map(m=><button className={selected===m.id?'active':''} onClick={()=>{setDefaultId(m.id);void userService.setDefaultPaymentMethod(m.id);notify('기본 결제 수단을 변경했어요');}} key={m.id}><i style={{background:m.brandBg,color:m.brandColor}}>{m.brandInitial}</i><span><b>{m.brand}</b>{selected===m.id&&<em>기본</em>}<small>{m.last4}</small></span><strong/></button>)}</div><h3>결제 내역</h3><div className="menu-box">{data.history.map(h=><div className="settle-row" key={h.id}><span><b>{h.description}</b><small>{h.date} · {h.method}</small></span><em>{h.amount}</em></div>)}</div>{toast&&<div className="done-toast" aria-live="polite">{toast}</div>}</div>}
