import { Award, Check, ChevronRight, CircleCheck, Copy, Eye, PartyPopper, Share2, Star, Trophy } from 'lucide-react';
import { useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { PageHeader } from '../components/common/PageHeader';

const people=[['김','김서연',92],['이','이준호',78],['박','박민지',88],['최','최유진',64],['정','정하늘',55]] as const;
const questions=[['노션 데이터베이스의 핵심 구성 요소는?',['페이지와 속성','폴더와 파일','셀과 시트','슬라이드와 도형'],0],['반복 업무를 자동화할 때 가장 먼저 할 일은?',['도구 구매','반복 과정 정의','팀원 채용','디자인 변경'],1]] as const;
export function ExamResultPage(){const {id='notion'}=useParams();return <div className="page subpage"><PageHeader title="최종 수료 시험" subtitle="응시 19명 · 합격 기준 70점"/><div className="score-overview"><div><b>82</b><small>평균 점수</small></div><div><b>14</b><small>합격</small></div><div><b>5</b><small>불합격</small></div></div><Link className="soft-primary" to={`/classes/${id}/exam-builder`}>문항 수정</Link><h3>응시자 결과</h3>{people.map(([initial,name,score],i)=><Link className="score-row" to={`/classes/${id}/exams/final/${i}`} key={name}><i>{initial}</i><span><b>{name}</b><small>제출 완료</small></span><strong className={score<70?'fail':''}>{score}점</strong><em>{score>=70?'합격':'불합격'}</em><ChevronRight/></Link>)}</div>}
export function ExamTakerPage(){return <div className="page subpage"><PageHeader title="김서연님의 답안" subtitle="최종 수료 시험 · 92점 · 합격"/><div className="answer-summary"><CircleCheck/><span><b>10문제 중 9문제 정답</b><small>2026. 07. 14 오후 8:42 제출</small></span></div>{questions.map(([text,choices,answer],i)=><article className="answer-card" key={text}><b>{i+1}. {text}</b>{choices.map((choice,j)=><p className={j===answer?'correct':j===answer+1&&i===1?'wrong':''} key={choice}><i>{j===answer?<Check/>:String.fromCharCode(65+j)}</i>{choice}{j===answer&&<em>정답</em>}</p>)}</article>)}</div>}
export function CertificateSetupPage(){const [attendance,setAttendance]=useState(80);const [score,setScore]=useState(70);const [message,setMessage]=useState('위 사람은 본 과정을 성실히 이수하였기에 이 수료증을 수여합니다.');return <div className="page subpage"><PageHeader title="수료증 설정" subtitle="발급 조건과 수료증 문구를 정해요"/><section className="cert-preview-mini"><Award/><small>CERTIFICATE</small><h2>수료증</h2><p>{message}</p><b>노션으로 시작하는 업무 자동화</b></section><label className="range-label">최소 출석률 <b>{attendance}%</b><input type="range" min="50" max="100" step="5" value={attendance} onChange={e=>setAttendance(Number(e.target.value))}/></label><label className="range-label">시험 합격 점수 <b>{score}점</b><input type="range" min="0" max="100" step="5" value={score} onChange={e=>setScore(Number(e.target.value))}/></label><label className="field-label">수료증 문구<textarea value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="primary">설정 저장</button></div>}
export function AttendPickerPage(){const today=['notion','노션으로 시작하는 업무 자동화','오후 8:00','2회차','24'];const others=[['calligraphy','주말 원데이 캘리그라피 클래스','1회차','15'],['branding','나만의 브랜드 만들기','3회차','20']];return <div className="page subpage attendance-picker"><PageHeader title="어떤 강의의 출석을 받을까요?" subtitle="오늘 진행하는 강의를 선택하면 QR이 열려요"/><div className="picker-label today">오늘 강의</div><Link className="pick-class today-card" to={`/classes/${today[0]}/attendance/qr`}><i/><span><em>오늘 {today[2]}</em><b>{today[1]}</b><small>{today[3]} · 수강생 {today[4]}명</small></span><ChevronRight/></Link><div className="picker-label">진행중인 다른 강의</div>{others.map((c,i)=><Link className="pick-class" to={`/classes/${c[0]}/attendance/qr`} key={c[0]}><i className={i?'purple':'green'}/><span><b>{c[1]}</b><small>{c[2]} · 수강생 {c[3]}명</small></span><ChevronRight/></Link>)}</div>}
export function StudentFlowPage(){const path=useLocation().pathname;const exam=path.includes('/exam/');const result=path.endsWith('/done')||path.endsWith('/result');const [index,setIndex]=useState(0);const [answer,setAnswer]=useState<number>();const survey=['강의 전반에 만족하시나요?','강사의 설명은 이해하기 쉬웠나요?','가장 좋았던 점을 알려주세요'];if(result)return <div className="page flow-result">{exam?<Trophy/>:<CircleCheck/>}<h1>{exam?'시험을 완료했어요!':'설문 응답이 제출됐어요'}</h1><p>{exam?'총점 80점으로 합격했어요.':'소중한 의견 감사합니다.'}</p>{exam&&<div className="result-ring"><b>80</b><small>점</small></div>}<Link className="primary" to="/">확인</Link></div>;const total=exam?questions.length:survey.length;const text=exam?questions[index][0]:survey[index];const choices=exam?questions[index][1]:['매우 만족','만족','보통','아쉬워요'];return <div className="page student-flow"><header><button onClick={()=>history.back()}>‹</button><b>{exam?'최종 수료 시험':'강의 만족도 설문'}</b><Link to="/">닫기</Link></header><div className="flow-progress"><i style={{width:`${(index+1)/total*100}%`}}/></div><small className="flow-count">{index+1} / {total}</small><h1>{text}</h1>{!exam&&index<2&&<div className="stars">{[1,2,3,4,5].map(n=><button onClick={()=>setAnswer(n)} className={(answer??0)>=n?'on':''} key={n}><Star fill="currentColor"/></button>)}</div>}{exam&&<div className="choice-list">{choices.map((c,i)=><button className={answer===i?'active':''} onClick={()=>setAnswer(i)} key={c}><i>{String.fromCharCode(65+i)}</i>{c}</button>)}</div>}{!exam&&index===2&&<textarea className="student-text" placeholder="자유롭게 의견을 남겨주세요"/>}<button className="primary flow-cta" disabled={answer===undefined&&index<2} onClick={()=>{setAnswer(undefined);setIndex(Math.min(index+1,total-1))}}>{index===total-1?<Link to={exam?'result':'done'}>제출하기</Link>:'다음'}</button></div>}
export function PublishDonePage(){return <div className="page publish-done"><PartyPopper/><h1>클래스가 공개됐어요!</h1><p>이제 링크를 공유하고<br/>수강생의 신청을 받아보세요.</p><div className="published-link"><span>oneclick.class/c/9Xk2p</span><button><Copy/>복사</button></div><div className="share-actions"><button><i>k</i>카카오톡</button><button><Share2/>더보기</button></div><Link className="secondary" to="/classes/notion/preview"><Eye/>신청 페이지 보기</Link><Link className="primary" to="/">홈으로</Link></div>}
