import { Award, Check, ClipboardList, Copy, Eye, Minus, Plus, QrCode, Settings, Star, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { ApplicantRow } from '../components/feature/ApplicantRow';
import { PageHeader } from '../components/common/PageHeader';
import { applicants } from '../constants/mockData';
import { FileDropzone } from '../components/ui';
import { classService } from '../api/services';
import { getClassThumbnail, readImageFile, saveClassThumbnail } from '../utils/classThumbnail';

type Config={title:string;subtitle:string;kind:'people'|'attendance'|'survey'|'exams'|'builder'|'settings'|'certificates'};
const configs:Record<string,Config>={applicants:{title:'신청자 관리',subtitle:'노션으로 시작하는 업무 자동화',kind:'people'},attendance:{title:'출석 관리',subtitle:'노션으로 시작하는 업무 자동화',kind:'attendance'},survey:{title:'설문',subtitle:'노션으로 시작하는 업무 자동화',kind:'survey'},exams:{title:'시험',subtitle:'노션으로 시작하는 업무 자동화',kind:'exams'},'survey-builder':{title:'설문 만들기',subtitle:'수강생에게 물어볼 질문을 만들어요',kind:'builder'},'exam-builder':{title:'시험 만들기',subtitle:'정답을 표시하면 자동 채점돼요',kind:'builder'},manage:{title:'강의 관리',subtitle:'노션으로 시작하는 업무 자동화',kind:'settings'},certificates:{title:'수료증 관리',subtitle:'조건과 수료증 내용을 직접 설정할 수 있어요',kind:'certificates'}};

export function ClassOperationsPage(){const key=useLocation().pathname.split('/').pop()??'';const cfg=configs[key]??configs.applicants;const {id='notion'}=useParams();const [toast,setToast]=useState('');const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2000);};return <><div className="oc-web-page"><WebClassChrome id={id} active={cfg.kind}/>{cfg.kind==='people'&&<WebPeople/>}{cfg.kind==='attendance'&&<WebAttendance/>}{(cfg.kind==='survey'||cfg.kind==='exams'||cfg.kind==='builder')&&<WebSurvey/>}{cfg.kind==='settings'&&<WebManage id={id} notify={notify}/>} {cfg.kind==='certificates'&&<WebCertificates notify={notify}/>} {toast&&<div className="done-toast" aria-live="polite">{toast}</div>}</div><div className="page subpage operations original-operations"><PageHeader title={cfg.title} subtitle={cfg.subtitle} backTo={`/classes/${id}`}/>{cfg.kind==='people'&&<People/>}{cfg.kind==='attendance'&&<Attendance id={id}/>} {cfg.kind==='survey'&&<Survey id={id}/>} {cfg.kind==='exams'&&<Exams id={id}/>} {cfg.kind==='builder'&&<Builder exam={key.startsWith('exam')} notify={notify}/>} {cfg.kind==='settings'&&<Manage id={id} notify={notify}/>} {cfg.kind==='certificates'&&<Certificates notify={notify}/>} {toast&&<div className="done-toast" aria-live="polite">{toast}</div>}</div></>}

function WebClassChrome({id,active}:{id:string;active:Config['kind']}){const thumbnail=getClassThumbnail(id);const tabs:[string,string,Config['kind']][]=[['개요',`/classes/${id}`,'settings'],['신청자',`/classes/${id}/applicants`,'people'],['출석/QR',`/classes/${id}/attendance`,'attendance'],['설문·시험',`/classes/${id}/survey`,'survey'],['수료증',`/classes/${id}/certificates`,'certificates']];return <><Link className="oc-back-link" to="/classes">‹ 클래스 목록</Link><section className="oc-detail-hero compact"><div className="oc-detail-cover" style={thumbnail?{backgroundImage:`url(${thumbnail})`}:undefined}><span>모집중 · 온라인</span></div><div className="oc-detail-body"><div className="oc-detail-title"><div><h1>노션으로 시작하는 업무 자동화</h1><p>노션 하나로 팀 업무를 자동화하는 4주 클래스</p></div><div><Link to={`/classes/${id}/manage`}>수정</Link><Link className="primary-link" to={`/classes/${id}/applicants`}>신청자 관리</Link></div></div><div className="oc-detail-tabs">{tabs.map(([label,to,kind])=><Link className={active===kind?'active':''} to={to} key={label}>{label}</Link>)}</div></div></section></>}

function WebPeople(){return <div className="oc-table"><div className="oc-table-head"><span>신청자</span><span>클래스</span><span>신청일</span><span>결제</span><span>금액</span></div>{applicants.map((a,i)=><div className="oc-table-row" key={a.id}><span style={{display:'flex',alignItems:'center',gap:12}}><span className="oc-avatar" style={{background:['#ffe9d9','#e7f0ff','#edebff'][i%3],color:['#e8590c','#1b64da','#6741d9'][i%3]}}>{a.name[0]}</span><strong>{a.name}</strong></span><span>{a.classTitle}</span><span>{a.appliedAt}</span><span className="oc-status" style={{color:a.payment==='결제대기'?'#e8590c':'#0ca678',background:a.payment==='결제대기'?'#fff4ec':'#e6f9f1'}}>{a.payment}</span><span>{a.amount.toLocaleString()}원</span></div>)}</div>}

function WebAttendance(){return <div className="oc-grid-2"><div className="oc-panel oc-qr-panel"><h2>실시간 출석 QR</h2><div className="oc-fake-qr">QR</div><p>남은 시간 <b>04:32</b></p><strong>18 <small>/ 20명 체크인</small></strong><button>QR 새로고침</button></div><div className="oc-panel"><div className="oc-panel-title"><h2>출석 명단</h2><span>3주차 · 2월 14일</span></div>{['김서연','이준호','박민지','최유진','정하늘','한지우'].map((name,i)=><div className="oc-attend-row" key={name}><span className="oc-avatar" style={{background:'#eff6ff',color:'#3182f6'}}>{name[0]}</span><b>{name}</b><small>{i===4?'-':'10:0'+i}</small><em className={i===4?'bad':i===3?'late':''}>{i===4?'결석':i===3?'지각':'출석'}</em></div>)}</div></div>}

function WebSurvey(){const cards=[['중간 만족도 설문','5문항 · 익명','진행중','65%'],['3주차 퀴즈','10문항 · 70점 이상 통과','마감','90%'],['최종 시험','20문항 · 60분','예정','0%'],['수료 후기 설문','3문항 · 공개','진행중','40%']];return <div className="oc-card-grid">{cards.map(([title,meta,status,pct])=><div className="oc-panel" key={title}><div className="oc-panel-title"><h2>{title}</h2><span className="oc-status" style={{color:'#3182f6',background:'#eff6ff'}}>{status}</span></div><p className="oc-muted-line">{meta}</p><div className="oc-progress"><i style={{width:pct}}/></div><p className="oc-muted-line">응답 {pct} · 결과 확인 가능</p><button className="oc-soft-button">결과 보기</button></div>)}</div>}

function WebManage({id,notify}:{id:string;notify:(message:string)=>void}){const [publicOn,setPublicOn]=useState(true);const [closed,setClosed]=useState(false);const [capacity,setCapacity]=useState(30);const [thumbnail,setThumbnail]=useState(()=>getClassThumbnail(id));const changeThumbnail=async(file:File)=>{const value=await readImageFile(file);setThumbnail(value);saveClassThumbnail(id,value);await classService.update(id,{thumbnail:value});notify('클래스 썸네일을 변경했어요');};return <><section className="oc-panel oc-thumbnail-editor"><div><h2>클래스 썸네일</h2><p>목록과 클래스 상세 상단에 표시되는 대표 이미지예요.</p></div>{thumbnail&&<img src={thumbnail} alt="현재 클래스 썸네일"/>}<FileDropzone onFile={(file)=>void changeThumbnail(file)}/></section><div className="oc-grid-2"><section className="oc-panel oc-settings-panel"><h2>강의 설정</h2><div><span><b>공개 상태</b><small>신청 페이지 노출</small></span><button className={`switch ${publicOn?'on':''}`} onClick={()=>{setPublicOn(!publicOn);notify(publicOn?'비공개로 전환했어요':'공개로 전환했어요');}}><i/></button></div><div><span><b>모집 상태</b><small>{closed?'신청을 받지 않아요':'현재 신청을 받고 있어요'}</small></span><button className="oc-soft-button" onClick={()=>{setClosed(!closed);notify(closed?'모집을 다시 열었어요':'모집을 마감했어요');}}>{closed?'모집 재개':'모집 마감'}</button></div><div><span><b>정원</b><small>현재 24명 신청</small></span><em><button onClick={()=>setCapacity(Math.max(25,capacity-5))}>−</button>{capacity}명<button onClick={()=>setCapacity(capacity+5)}>＋</button></em></div></section><section className="oc-panel"><h2>관리 메뉴</h2><div className="oc-menu-list"><Link to={`/classes/new?edit=${id}`}>강의 정보 수정 <span>›</span></Link><button onClick={()=>notify('신청서 수정 화면을 열었어요')}>신청서 수정 <span>›</span></button><button onClick={()=>notify('신청 링크를 복사했어요')}><Copy size={18}/> 신청 링크 복사 <span>›</span></button><button className="danger" onClick={()=>notify('삭제 전 확인이 필요해요')}>강의 삭제</button></div></section></div></>}

function WebCertificates({notify}:{notify:(message:string)=>void}){return <div className="oc-grid-2"><div className="oc-panel oc-cert-preview"><h2>수료증 미리보기</h2><div><b>CERTIFICATE</b><strong>수료증</strong><p>홍길동 님은 「노션 업무 자동화」 과정을 성실히 수료하였습니다.</p><small>2026.03.15 · 원클릭 클래스</small></div></div><div className="oc-panel"><div className="oc-panel-title"><h2>발급 대상</h2><button className="oc-create" onClick={()=>notify('수료증을 일괄 발급했어요')}>일괄 발급</button></div>{applicants.map((a,i)=><div className="oc-attend-row" key={a.id}><span className="oc-avatar" style={{background:'#eff6ff',color:'#3182f6'}}>{a.name[0]}</span><b>{a.name}<small>진도 {i?92:100}%</small></b><em>{i?'발급대기':'발급완료'}</em></div>)}</div></div>}

function People(){const [filter,setFilter]=useState('전체');const [query,setQuery]=useState('');const list=applicants.filter(a=>(filter==='전체'||a.payment===filter)&&a.name.includes(query));return <><div className="operation-stats"><div className="blue"><small>전체 신청</small><b>24<em>명</em></b></div><div className="orange"><small>결제 대기</small><b>3<em>건</em></b></div><div className="green"><small>결제 완료</small><b>21<em>명</em></b></div></div><input className="operation-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름·전화번호로 검색"/><div className="chips">{[['전체','24'],['결제대기','3'],['결제완료','21'],['환불','0']].map(([x,n])=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x} <span>{n}</span></button>)}</div>{list.map((a,i)=><ApplicantRow item={a} index={i} key={a.id}/>)}</>}

function Attendance({id}:{id:string}){const [session,setSession]=useState(2);const [absent,setAbsent]=useState<string[]>([]);return <><div className="operation-stats attendance-stats"><div className="blue"><small>전체 수강생</small><b>24<em>명</em></b></div><div className="green"><small>출석</small><b>22<em>명</em></b></div><div className="orange"><small>결석</small><b>2<em>명</em></b></div></div><Link className="qr-callout" to={`/classes/${id}/attendance/qr`}><QrCode/><span><b>출석 QR 열기</b><small>오늘 오후 8:00 · 2회차</small></span></Link><div className="chips session-chips">{[1,2,3,4].map(n=><button className={session===n?'active':''} onClick={()=>setSession(n)} key={n}>{n}회차</button>)}</div><h3 className="list-heading">2회차 출석 현황 <small>7월 15일</small></h3>{['김서연','이준호','박민지','최유진'].map(name=><button className="check-row" onClick={()=>setAbsent(absent.includes(name)?absent.filter(x=>x!==name):[...absent,name])} key={name}><span>{name[0]}</span><b>{name}</b><em className={absent.includes(name)?'absent':''}>{absent.includes(name)?'결석':'출석'}</em></button>)}</>}

function Survey({id}:{id:string}){return <><Link className="soft-primary" to={`/classes/${id}/survey-builder`}><Plus/>설문 문항 만들기 · 수정</Link><section className="survey-overview"><div><small>응답</small><b>18<em>/ 24명</em></b></div><div><small>전체 만족도</small><b>4.8</b><span><Star fill="currentColor"/> 5.0</span></div></section>{['강의 내용은 만족스러웠나요?','강사의 설명은 이해하기 쉬웠나요?'].map((q,i)=><article className="survey-result" key={q}><b>{i+1}. {q}</b>{[['매우 만족',72],['만족',18],['보통',10]].map(([label,pct])=><p key={label}><span>{label}</span><i><em style={{width:`${pct}%`}}/></i><small>{pct}%</small></p>)}</article>)}<article className="survey-comments"><b>3. 가장 좋았던 점을 알려주세요</b><p>실제 업무에 바로 활용할 수 있어서 좋았어요.</p><p>예제가 구체적이고 설명이 쉬웠습니다.</p></article></>}

function Exams({id}:{id:string}){return <><Link className="soft-primary" to={`/classes/${id}/exam-builder`}><Plus/>새 시험 만들기</Link><div className="operation-stats exam-stats"><div className="blue"><small>전체 응시</small><b>19<em>명</em></b></div><div className="green"><small>합격</small><b>14<em>명</em></b></div><div className="orange"><small>평균 점수</small><b>82<em>점</em></b></div></div>{['중간 점검 퀴즈','최종 수료 시험'].map((x,i)=><Link to={`/classes/${id}/exams/${i?'final':'mid'}`} className="exam-card" key={x}><ClipboardList/><span><b>{x}</b><small>{i?'응시 19명 · 평균 82점':'응시 24명 · 평균 86점'}</small></span><em>{i?'진행중':'완료'}</em></Link>)}</>}

function Builder({exam,notify}:{exam:boolean;notify:(message:string)=>void}){const nav=useNavigate();const [questions,setQuestions]=useState(['']);const [pass,setPass]=useState(70);const remove=(index:number)=>setQuestions(questions.length===1?['']:questions.filter((_,j)=>j!==index));return <>{exam&&<><label className="builder-title">시험 이름<input placeholder="예) 1주차 · 노션 기본 개념"/></label><div className="pass-score"><b>합격 기준 점수</b><span><button onClick={()=>setPass(Math.max(0,pass-5))}><Minus/></button><strong>{pass}점</strong><button onClick={()=>setPass(Math.min(100,pass+5))}><Plus/></button></span></div></>}{questions.map((q,i)=><article className="builder-card original-builder" key={i}><header><small>{exam?'문제':'Q'} {i+1}</small><button aria-label="문항 삭제" onClick={()=>remove(i)}><X/></button></header><input value={q} onChange={e=>setQuestions(questions.map((x,j)=>j===i?e.target.value:x))} placeholder={exam?'문제를 입력하세요':'질문을 입력하세요'}/>{!exam&&<div className="question-types"><button className="active">객관식</button><button>별점</button><button>서술형</button></div>}<small className="option-label">{exam?'보기 · 정답을 탭하세요':'선택지'}</small>{['보기 1','보기 2',...(exam?['보기 3','보기 4']:[])].map((x,j)=><label className="builder-option" key={x}><input type="radio" name={`answer-${i}`} defaultChecked={exam&&j===0}/><input placeholder={x}/>{!exam&&<button aria-label="선택지 삭제" onClick={()=>notify('선택지를 삭제했어요')}><X/></button>}</label>)}{!exam&&<button className="add-option" onClick={()=>notify('선택지를 추가했어요')}><Plus/>선택지 추가</button>}</article>)}<button className="outline-add" onClick={()=>setQuestions([...questions,''])}><Plus/>{exam?'문제':'질문'} 추가</button><button className="primary" onClick={()=>notify(`${exam?'시험':'설문'}을 저장했어요`)}>{exam?'시험':'설문'} 저장하기</button><button className="builder-preview" onClick={()=>nav(exam?'/learn/exam/take':'/learn/survey/take')}><Eye/>학생 화면으로 미리보기</button>{exam&&<button className="danger" onClick={()=>notify('시험을 삭제했어요')}>이 시험 삭제</button>}</>}

function Manage({id,notify}:{id:string;notify:(message:string)=>void}){const [publicOn,setPublicOn]=useState(true);const [closed,setClosed]=useState(false);const [capacity,setCapacity]=useState(30);return <><Link className="thumbnail-manage-link" to={`/classes/new?edit=${id}`}>썸네일·강의 정보 수정 <span>›</span></Link><section className="settings-card"><div><span><b>공개 상태</b><small>신청 페이지 노출</small></span><button className={`switch ${publicOn?'on':''}`} onClick={()=>{setPublicOn(!publicOn);notify(publicOn?'비공개로 전환했어요':'공개로 전환했어요');}}><i/></button></div><div><span><b>모집 상태</b><small>{closed?'신청을 받지 않아요':'현재 신청을 받고 있어요'}</small></span><button className="badge blue" onClick={()=>{setClosed(!closed);notify(closed?'모집을 다시 열었어요':'모집을 마감했어요');}}>{closed?'모집 재개':'모집 마감'}</button></div><div><span><b>정원</b><small>현재 24명 신청</small></span><em><button onClick={()=>setCapacity(Math.max(25,capacity-5))}>−</button>{capacity}명<button onClick={()=>setCapacity(capacity+5)}>＋</button></em></div></section><section className="menu-box"><Link to={`/classes/new?edit=${id}`}><span>강의 정보 수정</span>›</Link><button onClick={()=>notify('신청서 수정 화면을 열었어요')}><span>신청서 수정</span>›</button><button onClick={()=>{void navigator.clipboard?.writeText(`${location.origin}/classes/notion/enroll`);notify('신청 링크를 복사했어요');}}><Copy/><span>신청 링크 복사</span>›</button></section><button className="danger" onClick={()=>notify('삭제 전 확인이 필요해요')}>강의 삭제</button></>}

function Certificates({notify}:{notify:(message:string)=>void}){const eligible=useMemo(()=>applicants.slice(1),[]);const [issued,setIssued]=useState(false);return <><Link className="certificate-banner" to="setup"><Award/><span><b>수료 조건</b><small>출석 80% 이상 · 시험 70점 이상<br/>조건 충족 시 발급 대기 등록</small></span><Settings/></Link><div className="mini-stats cert-issue-stats"><div>발급 대기<b>{issued?0:12}명</b></div><div>발급 완료<b>{issued?12:0}명</b></div></div>{eligible.map((a,i)=><div className="check-row" key={a.id}><span>{a.name[0]}</span><b>{a.name}<small>{i?'출석 92% · 시험 88점':'출석 100% · 시험 94점'}</small></b><em><Check/>{issued||i?'완료':'발급'}</em></div>)}<button className="primary" onClick={()=>{setIssued(true);notify('수료증을 일괄 발급했어요');}}>대기 12명 일괄 발급</button></>}
