import { Award, Check, ClipboardList, Copy, Eye, Minus, Plus, QrCode, Settings, Star, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { ApplicantRow } from '../components/feature/ApplicantRow';
import { PageHeader } from '../components/common/PageHeader';
import { applicants } from '../constants/mockData';

type Config={title:string;subtitle:string;kind:'people'|'attendance'|'survey'|'exams'|'builder'|'settings'|'certificates'};
const configs:Record<string,Config>={applicants:{title:'신청자 관리',subtitle:'노션으로 시작하는 업무 자동화',kind:'people'},attendance:{title:'출석 관리',subtitle:'노션으로 시작하는 업무 자동화',kind:'attendance'},survey:{title:'설문',subtitle:'노션으로 시작하는 업무 자동화',kind:'survey'},exams:{title:'시험',subtitle:'노션으로 시작하는 업무 자동화',kind:'exams'},'survey-builder':{title:'설문 만들기',subtitle:'수강생에게 물어볼 질문을 만들어요',kind:'builder'},'exam-builder':{title:'시험 만들기',subtitle:'정답을 표시하면 자동 채점돼요',kind:'builder'},manage:{title:'강의 관리',subtitle:'노션으로 시작하는 업무 자동화',kind:'settings'},certificates:{title:'수료증 관리',subtitle:'조건과 수료증 내용을 직접 설정할 수 있어요',kind:'certificates'}};

export function ClassOperationsPage(){const key=useLocation().pathname.split('/').pop()??'';const cfg=configs[key]??configs.applicants;const {id='notion'}=useParams();return <div className="page subpage operations original-operations"><PageHeader title={cfg.title} subtitle={cfg.subtitle}/>{cfg.kind==='people'&&<People/>}{cfg.kind==='attendance'&&<Attendance id={id}/>} {cfg.kind==='survey'&&<Survey id={id}/>} {cfg.kind==='exams'&&<Exams id={id}/>} {cfg.kind==='builder'&&<Builder exam={key.startsWith('exam')}/>} {cfg.kind==='settings'&&<Manage/>} {cfg.kind==='certificates'&&<Certificates/>}</div>}

function People(){const [filter,setFilter]=useState('전체');const [query,setQuery]=useState('');const list=applicants.filter(a=>(filter==='전체'||a.payment===filter)&&a.name.includes(query));return <><div className="operation-stats"><div className="blue"><small>전체 신청</small><b>24<em>명</em></b></div><div className="orange"><small>결제 대기</small><b>3<em>건</em></b></div><div className="green"><small>결제 완료</small><b>21<em>명</em></b></div></div><input className="operation-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름·전화번호로 검색"/><div className="chips">{[['전체','24'],['결제대기','3'],['결제완료','21'],['환불','0']].map(([x,n])=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x} <span>{n}</span></button>)}</div>{list.map((a,i)=><ApplicantRow item={a} index={i} key={a.id}/>)}</>}

function Attendance({id}:{id:string}){const [session,setSession]=useState(2);const [absent,setAbsent]=useState<string[]>([]);return <><div className="operation-stats attendance-stats"><div className="blue"><small>전체 수강생</small><b>24<em>명</em></b></div><div className="green"><small>출석</small><b>22<em>명</em></b></div><div className="orange"><small>결석</small><b>2<em>명</em></b></div></div><Link className="qr-callout" to={`/classes/${id}/attendance/qr`}><QrCode/><span><b>출석 QR 열기</b><small>오늘 오후 8:00 · 2회차</small></span></Link><div className="chips session-chips">{[1,2,3,4].map(n=><button className={session===n?'active':''} onClick={()=>setSession(n)} key={n}>{n}회차</button>)}</div><h3 className="list-heading">2회차 출석 현황 <small>7월 15일</small></h3>{['김서연','이준호','박민지','최유진'].map(name=><button className="check-row" onClick={()=>setAbsent(absent.includes(name)?absent.filter(x=>x!==name):[...absent,name])} key={name}><span>{name[0]}</span><b>{name}</b><em className={absent.includes(name)?'absent':''}>{absent.includes(name)?'결석':'출석'}</em></button>)}</>}

function Survey({id}:{id:string}){return <><Link className="soft-primary" to={`/classes/${id}/survey-builder`}><Plus/>설문 문항 만들기 · 수정</Link><section className="survey-overview"><div><small>응답</small><b>18<em>/ 24명</em></b></div><div><small>전체 만족도</small><b>4.8</b><span><Star fill="currentColor"/> 5.0</span></div></section>{['강의 내용은 만족스러웠나요?','강사의 설명은 이해하기 쉬웠나요?'].map((q,i)=><article className="survey-result" key={q}><b>{i+1}. {q}</b>{[['매우 만족',72],['만족',18],['보통',10]].map(([label,pct])=><p key={label}><span>{label}</span><i><em style={{width:`${pct}%`}}/></i><small>{pct}%</small></p>)}</article>)}<article className="survey-comments"><b>3. 가장 좋았던 점을 알려주세요</b><p>실제 업무에 바로 활용할 수 있어서 좋았어요.</p><p>예제가 구체적이고 설명이 쉬웠습니다.</p></article></>}

function Exams({id}:{id:string}){return <><Link className="soft-primary" to={`/classes/${id}/exam-builder`}><Plus/>새 시험 만들기</Link><div className="operation-stats exam-stats"><div className="blue"><small>전체 응시</small><b>19<em>명</em></b></div><div className="green"><small>합격</small><b>14<em>명</em></b></div><div className="orange"><small>평균 점수</small><b>82<em>점</em></b></div></div>{['중간 점검 퀴즈','최종 수료 시험'].map((x,i)=><Link to={`/classes/${id}/exams/${i?'final':'mid'}`} className="exam-card" key={x}><ClipboardList/><span><b>{x}</b><small>{i?'응시 19명 · 평균 82점':'응시 24명 · 평균 86점'}</small></span><em>{i?'진행중':'완료'}</em></Link>)}</>}

function Builder({exam}:{exam:boolean}){const [questions,setQuestions]=useState(['']);const [pass,setPass]=useState(70);return <>{exam&&<><label className="builder-title">시험 이름<input placeholder="예) 1주차 · 노션 기본 개념"/></label><div className="pass-score"><b>합격 기준 점수</b><span><button onClick={()=>setPass(Math.max(0,pass-5))}><Minus/></button><strong>{pass}점</strong><button onClick={()=>setPass(Math.min(100,pass+5))}><Plus/></button></span></div></>}{questions.map((q,i)=><article className="builder-card original-builder" key={i}><header><small>{exam?'문제':'Q'} {i+1}</small><button aria-label="문항 삭제" onClick={()=>setQuestions(questions.filter((_,j)=>j!==i))}><X/></button></header><input value={q} onChange={e=>setQuestions(questions.map((x,j)=>j===i?e.target.value:x))} placeholder={exam?'문제를 입력하세요':'질문을 입력하세요'}/>{!exam&&<div className="question-types"><button className="active">객관식</button><button>별점</button><button>서술형</button></div>}<small className="option-label">{exam?'보기 · 정답을 탭하세요':'선택지'}</small>{['보기 1','보기 2',...(exam?['보기 3','보기 4']:[])].map((x,j)=><label className="builder-option" key={x}><input type="radio" name={`answer-${i}`} defaultChecked={exam&&j===0}/><input placeholder={x}/>{!exam&&<button aria-label="선택지 삭제"><X/></button>}</label>)}{!exam&&<button className="add-option"><Plus/>선택지 추가</button>}</article>)}<button className="outline-add" onClick={()=>setQuestions([...questions,''])}><Plus/>{exam?'문제':'질문'} 추가</button><button className="primary">{exam?'시험':'설문'} 저장하기</button><button className="builder-preview"><Eye/>학생 화면으로 미리보기</button>{exam&&<button className="danger">이 시험 삭제</button>}</>}

function Manage(){const [publicOn,setPublicOn]=useState(true);const [capacity,setCapacity]=useState(30);return <><section className="settings-card"><div><span><b>공개 상태</b><small>신청 페이지 노출</small></span><button className={`switch ${publicOn?'on':''}`} onClick={()=>setPublicOn(!publicOn)}><i/></button></div><div><span><b>모집 상태</b><small>현재 신청을 받고 있어요</small></span><button className="badge blue">모집 마감</button></div><div><span><b>정원</b><small>현재 24명 신청</small></span><em><button onClick={()=>setCapacity(Math.max(25,capacity-5))}>−</button>{capacity}명<button onClick={()=>setCapacity(capacity+5)}>＋</button></em></div></section><section className="menu-box"><button><span>강의 정보 수정</span>›</button><button><span>신청서 수정</span>›</button><button><Copy/><span>신청 링크 복사</span>›</button></section><button className="danger">강의 삭제</button></>}

function Certificates(){const eligible=useMemo(()=>applicants.slice(1),[]);return <><Link className="certificate-banner" to="setup"><Award/><span><b>수료 조건</b><small>출석 80% 이상 · 시험 70점 이상<br/>조건 충족 시 발급 대기 등록</small></span><Settings/></Link><div className="mini-stats cert-issue-stats"><div>발급 대기<b>12명</b></div><div>발급 완료<b>0명</b></div></div>{eligible.map((a,i)=><div className="check-row" key={a.id}><span>{a.name[0]}</span><b>{a.name}<small>{i?'출석 92% · 시험 88점':'출석 100% · 시험 94점'}</small></b><em><Check/>{i?'발급':'완료'}</em></div>)}<button className="primary">대기 12명 일괄 발급</button></>}
