import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './styles/global.css';
import './styles/ui.css';
import './styles/advanced.css';
import './styles/create.css';
import './styles/shell.css';
import './styles/qr.css';
import './styles/design-fixes.css';
import './styles/web.css';
import './styles/auth-layout.css';
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
